name: "Download Artifact from Workflow"
description: "Download an artifact from a specific workflow run"
inputs:
  workflow:
    description: "Workflow file name (e.g., build.yml)"
    required: true
  artifact-name:
    description: "Name of the artifact to download"
    required: true
  destination:
    description: "Destination path for the downloaded artifact (without .zip extension)"
    required: true
  branch:
    description: "Branch to search for workflow runs"
    required: false
    default: "main"
  token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        set -xe

        ORG="${{ github.repository_owner }}"
        REPO="${{ github.repository }}"
        WORKFLOW="${{ inputs.workflow }}"
        ARTIFACT_NAME="${{ inputs.artifact-name }}"
        DESTINATION="${{ inputs.destination }}"
        BRANCH="${{ inputs.branch }}"

        ARTIFACTS_URL=$(
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${ORG}/${REPO}/actions/workflows/${WORKFLOW}/runs?event=push&branch=${BRANCH}&status=success&per_page=1" \
            --jq ".workflow_runs[0].artifacts_url"
        )

        DOWNLOAD_URL=$(
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${ARTIFACTS_URL}" \
            --jq '.artifacts[] | select(.name == "'${ARTIFACT_NAME}'") | .archive_download_url'
        )

        set +x
        curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ inputs.token }}" -L -o "${DESTINATION}.zip" "$DOWNLOAD_URL"
        set -x
