name: "Determine tag name"
description: "Determine the tag name to use for a release"
inputs:
  repo-path:
    type: string
    required: true

outputs:
  name:
    description: "The name of the tag"
    value: ${{ steps.tag.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Determine tag name
      id: tag
      shell: bash
      run: |
        cd ${{ inputs.repo-path }}
        BUILD_TAGS="$(git rev-list --tags --max-count=1)"
        BUILD_NUMBER="$(git describe --tags $BUILD_TAGS)"
        echo "name=${BUILD_NUMBER}" >> $GITHUB_OUTPUT
