name: "Determine tag name"
description: "Determine the tag name to use for a release"
inputs:
  repo-path:
    type: string
    required: true

outputs:
  name:
    description: "The name of the tag"
    value: ${{ steps.tag.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Determine tag name
      id: tag
      shell: bash
      run: |
        cd ${{ inputs.repo-path }}
        BUILD_NUMBER="$(git describe --abbrev=0 --tags)"
        echo "name=${BUILD_NUMBER}" >> $GITHUB_OUTPUT
