name: "Determine tag name"
description: "Determine the tag name to use for a release"
inputs:
  repo-path:
    type: string
    required: true

outputs:
  name:
    description: "The name of the tag"
    value: ${{ steps.tag.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Determine tag name
      id: tag
      shell: bash
      run: |
        cd ${{ inputs.repo-path }}
        # Get the most recent release tag (format: b followed by numbers)
        BUILD_NUMBER="$(git tag --sort=-version:refname | grep -E '^b[0-9]+$' | head -n 1 || true)"
        if [ -z "$BUILD_NUMBER" ]; then
          echo "No release tags found, using b0"
          BUILD_NUMBER="b0"
        fi
        echo "Found tag: $BUILD_NUMBER"
        echo "name=${BUILD_NUMBER}" >> $GITHUB_OUTPUT
